version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BUCKET_REPLENISH_RATE=2
      - BUCKET_CAPACITY=10
      - TOKENS_PER_REQUEST=1
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
