[project]
name = "rate-limiter-example"
version = "0.1.0"
description = "An example rate limited app built using FastAPI and Redis."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.4",
    "redis>=5.2.0",
    "uvicorn>=0.32.0",
]
